"""
Healthcare task definitions and profiles.

Each HealthcareTask represents one sensing/processing job generated by a
wearable device.  Task profiles are derived from published literature on
clinical-grade biosignal processing workloads.

References:
  - ECG workload: Pan-Tompkins + DNN classifier ≈ 12 M cycles, 5 MB data
  - SpO2: simple LED-ratio algorithm, ~500 K cycles, 5 KB data
  - BP (cuffless PPG): 2 M cycles, 50 KB data
  - Multi-vital fusion: aggregated pipeline, ~8 M cycles, 1 MB data
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class HealthcareTask:
    task_id: int
    device_id: int
    timestamp: float              # arrival time in seconds since simulation start
    data_size_bits: int           # D_i — raw data payload in bits
    cpu_cycles: int               # C_i — required CPU cycles for local processing
    max_delay_s: float            # T^{max}_i — SLA deadline in seconds
    privacy_sensitivity: float    # ρ_i ∈ [0, 1] — higher → more sensitive
    ci_score: float               # Φ_i ∈ [0, 1] — Criticality Index
    attack_probability: float = 0.0   # p_{atk,i} ∈ [0, 1] — adversarial threat level
    source: str = 'synthetic'         # 'synthetic' | 'physionet' | 'mimic'
    assigned_node: Optional[int] = None
    actual_latency_s: Optional[float] = None
    actual_energy_j: Optional[float] = None
    sla_violated: bool = False

    def __post_init__(self):
        # Clamp CI and privacy to [0, 1]
        self.ci_score = float(max(0.0, min(1.0, self.ci_score)))
        self.privacy_sensitivity = float(max(0.0, min(1.0, self.privacy_sensitivity)))
        self.attack_probability = float(max(0.0, min(1.0, self.attack_probability)))


# ---------------------------------------------------------------------------
# Clinical task profiles
# Keys map to task type strings used by the event generator.
# Values contain base parameters before per-task noise injection.
# ---------------------------------------------------------------------------
TASK_PROFILES = {
    # ECG arrhythmia analysis — Pan-Tompkins QRS + lightweight CNN classifier
    # Data: 5 s × 500 Hz × 16-bit = 40 Mb; Cycles: DNN inference ≈ 12 M
    'ecg_analysis': {
        'data_size_bits':     40_000_000,
        'cpu_cycles':         12_000_000,
        'max_delay_s':        0.5,           # real-time alarm threshold
        'privacy_sensitivity': 0.9,
    },

    # SpO2 monitoring — Beer-Lambert ratio algorithm, very lightweight
    # Data: 1 s × 25 Hz × 16-bit = 400 b ≈ rounded up to 40 Kb
    'spo2_monitoring': {
        'data_size_bits':         40_000,
        'cpu_cycles':            500_000,
        'max_delay_s':               2.0,
        'privacy_sensitivity':       0.6,
    },

    # Cuffless blood-pressure via PPG: feature extraction + regression model
    # Data: 5 s × 500 Hz × 16-bit = 40 Mb → compressed to ~400 Kb
    'bp_analysis': {
        'data_size_bits':        400_000,
        'cpu_cycles':          2_000_000,
        'max_delay_s':               1.0,
        'privacy_sensitivity':       0.8,
    },

    # Multi-vital fusion (ECG + SpO2 + BP) — aggregated pipeline
    # Data: compressed multi-channel stream ≈ 1 MB = 8 Mb
    'multi_vital': {
        'data_size_bits':      8_000_000,
        'cpu_cycles':          8_000_000,
        'max_delay_s':               0.8,
        'privacy_sensitivity':      0.85,
    },
}

# Default CI score per task type (used when not supplied externally)
DEFAULT_CI = {
    'ecg_analysis':    0.85,
    'spo2_monitoring': 0.4,
    'bp_analysis':     0.6,
    'multi_vital':     0.75,
}
